[profile.default]
src = "src"
out = "out"
libs = ["lib", "../../../swap/node_modules", "../../../swap/dependencies"]
solc_version = "0.8.26"
optimizer = true
optimizer_runs = 200
via_ir = true
remappings = [
  "forge-std/=../../../swap/dependencies/forge-std-1.9.7/src/",
  "@zetachain/toolkit/=../../../swap/node_modules/@zetachain/toolkit/",
  "@zetachain/protocol-contracts/=../../../swap/node_modules/@zetachain/protocol-contracts/",
  "@uniswap/=../../../swap/node_modules/@uniswap/",
]

[rpc_endpoints]
sepolia = "${SEPOLIA_RPC_URL}"
bsc_testnet = "${BSC_TESTNET_RPC_URL}"
zeta_testnet = "${ZETA_TESTNET_RPC_URL}"

[etherscan]
sepolia = { key = "${ETHERSCAN_API_KEY}" }
bsc_testnet = { key = "${BSCSCAN_API_KEY}" }

# See more config options https://github.com/foundry-rs/foundry/blob/master/crates/config/README.md#all-options
